#ifndef PROTO_FONTCONFIG_H
#define PROTO_FONTCONFIG_H

/*
** This file was machine generated by idltool.py 54.8.
** Do not edit.
**
** Prototype/inline/pragma header file combo.
*/

/****************************************************************************/

#ifndef __NOLIBBASE__
 #ifndef __USE_BASETYPE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::Library * FontconfigBase;
  #else
   extern struct Library * FontconfigBase;
  #endif
 #else
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::FontconfigLibrary * FontconfigBase;
  #else
   extern struct FontconfigLibrary * FontconfigBase;
  #endif
 #endif /* __USE_BASETYPE__ */
#endif /* __NOLIBBASE__ */

/****************************************************************************/

#ifdef __amigaos4__
 #include <interfaces/fontconfig.h>
 #ifdef __USE_INLINE__
  #include <inline4/fontconfig.h>
 #endif /* __USE_INLINE__ */
 #ifndef CLIB_FONTCONFIG_PROTOS_H
  #define CLIB_FONTCONFIG_PROTOS_H 1
 #endif /* CLIB_FONTCONFIG_PROTOS_H */
 #ifndef __NOGLOBALIFACE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::FontconfigIFace * IFontconfig;
  #else
   extern struct FontconfigIFace * IFontconfig;
  #endif
 #endif /* __NOGLOBALIFACE__ */
#else /* __amigaos4__ */
 #ifndef CLIB_FONTCONFIG_PROTOS_H
  #include <clib/fontconfig_protos.h>
 #endif /* CLIB_FONTCONFIG_PROTOS_H */
 #if defined(__GNUC__)
  #ifndef __PPC__
   #include <inline/fontconfig.h>
  #else /* __PPC__ */
   #include <ppcinline/fontconfig.h>
  #endif /* __PPC__ */
 #elif defined(__VBCC__)
  #ifndef __PPC__
   #include <inline/fontconfig_protos.h>
  #endif /* __PPC__ */
 #else /* __GNUC__ */
  #include <pragmas/fontconfig_pragmas.h>
 #endif /* __GNUC__ */
#endif /* __amigaos4__ */

/****************************************************************************/

#endif /* PROTO_FONTCONFIG_H */
