#ifndef FONTCONFIG_INTERFACE_DEF_H
#define FONTCONFIG_INTERFACE_DEF_H

/*
** This file was machine generated by idltool.py 54.8.
** Do not edit.
*/

#include <exec/types.h>
#include <exec/exec.h>
#include <exec/interfaces.h>

#include <fontconfig/fontconfig.h>
#include <freetype/freetype.h>

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct FontconfigIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct FontconfigIFace *Self);
	uint32 APICALL (*Release)(struct FontconfigIFace *Self);
	APTR Expunge_UNIMPLEMENTED;
	APTR Clone_UNIMPLEMENTED;
	int APICALL (*FcConfigGetRescanInverval)(struct FontconfigIFace *Self, FcConfig * config);
	FcBool APICALL (*FcConfigSetRescanInverval)(struct FontconfigIFace *Self, FcConfig * config, int rescanInterval);
	FT_UInt APICALL (*FcFreeTypeCharIndex)(struct FontconfigIFace *Self, FT_Face face, FcChar32 ucs4);
	FcCharSet * APICALL (*FcFreeTypeCharSetAndSpacing)(struct FontconfigIFace *Self, FT_Face face, FcBlanks * blanks, int * spacing);
	FcCharSet * APICALL (*FcFreeTypeCharSet)(struct FontconfigIFace *Self, FT_Face face, FcBlanks * blanks);
	FcResult APICALL (*FcPatternGetFTFace)(struct FontconfigIFace *Self, const FcPattern * p, const char * object, int n, FT_Face * f);
	FcBool APICALL (*FcPatternAddFTFace)(struct FontconfigIFace *Self, FcPattern * p, const char * object, const FT_Face f);
	FcPattern * APICALL (*FcFreeTypeQueryFace)(struct FontconfigIFace *Self, const FT_Face face, const FcChar8 * file, unsigned int id, FcBlanks * blanks);
	FcBlanks * APICALL (*FcBlanksCreate)(struct FontconfigIFace *Self);
	void APICALL (*FcBlanksDestroy)(struct FontconfigIFace *Self, FcBlanks * b);
	FcBool APICALL (*FcBlanksAdd)(struct FontconfigIFace *Self, FcBlanks * b, FcChar32 ucs4);
	FcBool APICALL (*FcBlanksIsMember)(struct FontconfigIFace *Self, FcBlanks * b, FcChar32 ucs4);
	const FcChar8 * APICALL (*FcCacheDir)(struct FontconfigIFace *Self, const FcCache * c);
	FcFontSet * APICALL (*FcCacheCopySet)(struct FontconfigIFace *Self, const FcCache * c);
	const FcChar8 * APICALL (*FcCacheSubdir)(struct FontconfigIFace *Self, const FcCache * c, int i);
	int APICALL (*FcCacheNumSubdir)(struct FontconfigIFace *Self, const FcCache * c);
	int APICALL (*FcCacheNumFont)(struct FontconfigIFace *Self, const FcCache * c);
	FcBool APICALL (*FcDirCacheUnlink)(struct FontconfigIFace *Self, const FcChar8 * dir, FcConfig * config);
	FcBool APICALL (*FcDirCacheValid)(struct FontconfigIFace *Self, const FcChar8 * cache_file);
	FcBool APICALL (*FcDirCacheClean)(struct FontconfigIFace *Self, const FcChar8 * cache_dir, FcBool verbose);
	void APICALL (*FcCacheCreateTagFile)(struct FontconfigIFace *Self, FcConfig * config);
	FcBool APICALL (*FcDirCacheCreateUUID)(struct FontconfigIFace *Self, FcChar8 * dir, FcBool force, FcConfig * config);
	FcBool APICALL (*FcDirCacheDeleteUUID)(struct FontconfigIFace *Self, const FcChar8 * dir, FcConfig * config);
	FcChar8 * APICALL (*FcConfigHome)(struct FontconfigIFace *Self);
	FcBool APICALL (*FcConfigEnableHome)(struct FontconfigIFace *Self, FcBool enable);
	FcChar8 * APICALL (*FcConfigGetFilename)(struct FontconfigIFace *Self, FcConfig * config, const FcChar8 * url);
	FcChar8 * APICALL (*FcConfigFilename)(struct FontconfigIFace *Self, const FcChar8 * url);
	FcConfig * APICALL (*FcConfigCreate)(struct FontconfigIFace *Self);
	FcConfig * APICALL (*FcConfigReference)(struct FontconfigIFace *Self, FcConfig * config);
	void APICALL (*FcConfigDestroy)(struct FontconfigIFace *Self, FcConfig * config);
	FcBool APICALL (*FcConfigSetCurrent)(struct FontconfigIFace *Self, FcConfig * config);
	FcConfig * APICALL (*FcConfigGetCurrent)(struct FontconfigIFace *Self);
	FcBool APICALL (*FcConfigUptoDate)(struct FontconfigIFace *Self, FcConfig * config);
	FcBool APICALL (*FcConfigBuildFonts)(struct FontconfigIFace *Self, FcConfig * config);
	FcStrList * APICALL (*FcConfigGetFontDirs)(struct FontconfigIFace *Self, FcConfig * config);
	FcStrList * APICALL (*FcConfigGetConfigDirs)(struct FontconfigIFace *Self, FcConfig * config);
	FcStrList * APICALL (*FcConfigGetConfigFiles)(struct FontconfigIFace *Self, FcConfig * config);
	FcChar8 * APICALL (*FcConfigGetCache)(struct FontconfigIFace *Self, FcConfig * config);
	FcBlanks * APICALL (*FcConfigGetBlanks)(struct FontconfigIFace *Self, FcConfig * config);
	FcStrList * APICALL (*FcConfigGetCacheDirs)(struct FontconfigIFace *Self, FcConfig * config);
	int APICALL (*FcConfigGetRescanInterval)(struct FontconfigIFace *Self, FcConfig * config);
	FcBool APICALL (*FcConfigSetRescanInterval)(struct FontconfigIFace *Self, FcConfig * config, int rescanInterval);
	FcFontSet * APICALL (*FcConfigGetFonts)(struct FontconfigIFace *Self, FcConfig * config, FcSetName set);
	FcBool APICALL (*FcConfigAcceptFont)(struct FontconfigIFace *Self, FcConfig * config, const FcPattern * font);
	FcBool APICALL (*FcConfigAppFontAddFile)(struct FontconfigIFace *Self, FcConfig * config, const FcChar8 * file);
	FcBool APICALL (*FcConfigAppFontAddDir)(struct FontconfigIFace *Self, FcConfig * config, const FcChar8 * dir);
	void APICALL (*FcConfigAppFontClear)(struct FontconfigIFace *Self, FcConfig * config);
	FcBool APICALL (*FcConfigSubstituteWithPat)(struct FontconfigIFace *Self, FcConfig * config, FcPattern * p, FcPattern * p_pat, FcMatchKind kind);
	FcBool APICALL (*FcConfigSubstitute)(struct FontconfigIFace *Self, FcConfig * config, FcPattern * p, FcMatchKind kind);
	const FcChar8 * APICALL (*FcConfigGetSysRoot)(struct FontconfigIFace *Self, const FcConfig * config);
	void APICALL (*FcConfigSetSysRoot)(struct FontconfigIFace *Self, FcConfig * config, const FcChar8 * sysroot);
	void APICALL (*FcConfigFileInfoIterInit)(struct FontconfigIFace *Self, FcConfig * config, FcConfigFileInfoIter * iter);
	FcBool APICALL (*FcConfigFileInfoIterNext)(struct FontconfigIFace *Self, FcConfig * config, FcConfigFileInfoIter * iter);
	FcBool APICALL (*FcConfigFileInfoIterGet)(struct FontconfigIFace *Self, FcConfig * config, FcConfigFileInfoIter * iter, FcChar8 * *name, FcChar8 * *description, FcBool * enabled);
	FcCharSet* APICALL (*FcCharSetCreate)(struct FontconfigIFace *Self);
	FcCharSet * APICALL (*FcCharSetNew)(struct FontconfigIFace *Self);
	void APICALL (*FcCharSetDestroy)(struct FontconfigIFace *Self, FcCharSet * fcs);
	FcBool APICALL (*FcCharSetAddChar)(struct FontconfigIFace *Self, FcCharSet * fcs, FcChar32 ucs4);
	FcBool APICALL (*FcCharSetDelChar)(struct FontconfigIFace *Self, FcCharSet * fcs, FcChar32 ucs4);
	FcCharSet* APICALL (*FcCharSetCopy)(struct FontconfigIFace *Self, FcCharSet * src);
	FcBool APICALL (*FcCharSetEqual)(struct FontconfigIFace *Self, const FcCharSet * a, const FcCharSet * b);
	FcCharSet* APICALL (*FcCharSetIntersect)(struct FontconfigIFace *Self, const FcCharSet * a, const FcCharSet * b);
	FcCharSet* APICALL (*FcCharSetUnion)(struct FontconfigIFace *Self, const FcCharSet * a, const FcCharSet * b);
	FcCharSet* APICALL (*FcCharSetSubtract)(struct FontconfigIFace *Self, const FcCharSet * a, const FcCharSet * b);
	FcBool APICALL (*FcCharSetMerge)(struct FontconfigIFace *Self, FcCharSet * a, const FcCharSet * b, FcBool * changed);
	FcBool APICALL (*FcCharSetHasChar)(struct FontconfigIFace *Self, const FcCharSet * fcs, FcChar32 ucs4);
	FcChar32 APICALL (*FcCharSetCount)(struct FontconfigIFace *Self, const FcCharSet * a);
	FcChar32 APICALL (*FcCharSetIntersectCount)(struct FontconfigIFace *Self, const FcCharSet * a, const FcCharSet * b);
	FcChar32 APICALL (*FcCharSetSubtractCount)(struct FontconfigIFace *Self, const FcCharSet * a, const FcCharSet * b);
	FcBool APICALL (*FcCharSetIsSubset)(struct FontconfigIFace *Self, const FcCharSet * a, const FcCharSet * b);
	FcChar32 APICALL (*FcCharSetFirstPage)(struct FontconfigIFace *Self, const FcCharSet * a, FcChar32 map[FC_CHARSET_MAP_SIZE], FcChar32 * next);
	FcChar32 APICALL (*FcCharSetNextPage)(struct FontconfigIFace *Self, const FcCharSet * a, FcChar32 map[FC_CHARSET_MAP_SIZE], FcChar32 * next);
	FcChar32 APICALL (*FcCharSetCoverage)(struct FontconfigIFace *Self, const FcCharSet * a, FcChar32 page, FcChar32 * result);
	void APICALL (*FcValuePrint)(struct FontconfigIFace *Self, const FcValue v);
	void APICALL (*FcPatternPrint)(struct FontconfigIFace *Self, const FcPattern * p);
	void APICALL (*FcFontSetPrint)(struct FontconfigIFace *Self, const FcFontSet * s);
	FcStrSet * APICALL (*FcGetDefaultLangs)(struct FontconfigIFace *Self);
	void APICALL (*FcDefaultSubstitute)(struct FontconfigIFace *Self, FcPattern * pattern);
	FcBool APICALL (*FcFileIsDir)(struct FontconfigIFace *Self, const FcChar8 * file);
	FcBool APICALL (*FcFileScan)(struct FontconfigIFace *Self, FcFontSet * set, FcStrSet * dirs, FcFileCache * cache, FcBlanks * blanks, const FcChar8 * file, FcBool force);
	FcBool APICALL (*FcDirScan)(struct FontconfigIFace *Self, FcFontSet * set, FcStrSet * dirs, FcFileCache * cache, FcBlanks * blanks, const FcChar8 * dir, FcBool force);
	FcBool APICALL (*FcDirSave)(struct FontconfigIFace *Self, FcFontSet * set, FcStrSet * dirs, const FcChar8 * dir);
	FcCache * APICALL (*FcDirCacheLoad)(struct FontconfigIFace *Self, const FcChar8 * dir, FcConfig * config, FcChar8 * *cache_file);
	FcCache * APICALL (*FcDirCacheRescan)(struct FontconfigIFace *Self, const FcChar8 * dir, FcConfig * config);
	FcCache * APICALL (*FcDirCacheRead)(struct FontconfigIFace *Self, const FcChar8 * dir, FcBool force, FcConfig * config);
	FcCache * APICALL (*FcDirCacheLoadFile)(struct FontconfigIFace *Self, const FcChar8 * cache_file, struct stat * file_stat);
	void APICALL (*FcDirCacheUnload)(struct FontconfigIFace *Self, FcCache * cache);
	FcPattern * APICALL (*FcFreeTypeQuery)(struct FontconfigIFace *Self, const FcChar8 * file, unsigned int id, FcBlanks * blanks, int * count);
	unsigned int APICALL (*FcFreeTypeQueryAll)(struct FontconfigIFace *Self, const FcChar8 * file, unsigned int id, FcBlanks * blanks, int * count, FcFontSet * set);
	FcFontSet * APICALL (*FcFontSetCreate)(struct FontconfigIFace *Self);
	void APICALL (*FcFontSetDestroy)(struct FontconfigIFace *Self, FcFontSet * s);
	FcBool APICALL (*FcFontSetAdd)(struct FontconfigIFace *Self, FcFontSet * s, FcPattern * font);
	FcConfig * APICALL (*FcInitLoadConfig)(struct FontconfigIFace *Self);
	FcConfig * APICALL (*FcInitLoadConfigAndFonts)(struct FontconfigIFace *Self);
	FcBool APICALL (*FcInit)(struct FontconfigIFace *Self);
	void APICALL (*FcFini)(struct FontconfigIFace *Self);
	int APICALL (*FcGetVersion)(struct FontconfigIFace *Self);
	FcBool APICALL (*FcInitReinitialize)(struct FontconfigIFace *Self);
	FcBool APICALL (*FcInitBringUptoDate)(struct FontconfigIFace *Self);
	FcStrSet * APICALL (*FcGetLangs)(struct FontconfigIFace *Self);
	FcChar8 * APICALL (*FcLangNormalize)(struct FontconfigIFace *Self, const FcChar8 * lang);
	const FcCharSet * APICALL (*FcLangGetCharSet)(struct FontconfigIFace *Self, const FcChar8 * lang);
	FcLangSet* APICALL (*FcLangSetCreate)(struct FontconfigIFace *Self);
	void APICALL (*FcLangSetDestroy)(struct FontconfigIFace *Self, FcLangSet * ls);
	FcLangSet* APICALL (*FcLangSetCopy)(struct FontconfigIFace *Self, const FcLangSet * ls);
	FcBool APICALL (*FcLangSetAdd)(struct FontconfigIFace *Self, FcLangSet * ls, const FcChar8 * lang);
	FcBool APICALL (*FcLangSetDel)(struct FontconfigIFace *Self, FcLangSet * ls, const FcChar8 * lang);
	FcLangResult APICALL (*FcLangSetHasLang)(struct FontconfigIFace *Self, const FcLangSet * ls, const FcChar8 * lang);
	FcLangResult APICALL (*FcLangSetCompare)(struct FontconfigIFace *Self, const FcLangSet * lsa, const FcLangSet * lsb);
	FcBool APICALL (*FcLangSetContains)(struct FontconfigIFace *Self, const FcLangSet * lsa, const FcLangSet * lsb);
	FcBool APICALL (*FcLangSetEqual)(struct FontconfigIFace *Self, const FcLangSet * lsa, const FcLangSet * lsb);
	FcChar32 APICALL (*FcLangSetHash)(struct FontconfigIFace *Self, const FcLangSet * ls);
	FcStrSet * APICALL (*FcLangSetGetLangs)(struct FontconfigIFace *Self, const FcLangSet * ls);
	FcLangSet * APICALL (*FcLangSetUnion)(struct FontconfigIFace *Self, const FcLangSet * a, const FcLangSet * b);
	FcLangSet * APICALL (*FcLangSetSubtract)(struct FontconfigIFace *Self, const FcLangSet * a, const FcLangSet * b);
	FcObjectSet * APICALL (*FcObjectSetCreate)(struct FontconfigIFace *Self);
	FcBool APICALL (*FcObjectSetAdd)(struct FontconfigIFace *Self, FcObjectSet * os, const char * object);
	void APICALL (*FcObjectSetDestroy)(struct FontconfigIFace *Self, FcObjectSet * os);
	FcObjectSet * APICALL (*FcObjectSetVaBuild)(struct FontconfigIFace *Self, const char * first, va_list va);
	FcObjectSet * APICALL (*FcObjectSetBuild)(struct FontconfigIFace *Self, const char * first, ...);
	FcFontSet * APICALL (*FcFontSetList)(struct FontconfigIFace *Self, FcConfig * config, FcFontSet * *sets, int nsets, FcPattern * p, FcObjectSet * os);
	FcFontSet * APICALL (*FcFontList)(struct FontconfigIFace *Self, FcConfig * config, FcPattern * p, FcObjectSet * os);
	FcAtomic * APICALL (*FcAtomicCreate)(struct FontconfigIFace *Self, const FcChar8 * file);
	FcBool APICALL (*FcAtomicLock)(struct FontconfigIFace *Self, FcAtomic * atomic);
	FcChar8 * APICALL (*FcAtomicNewFile)(struct FontconfigIFace *Self, FcAtomic * atomic);
	FcChar8 * APICALL (*FcAtomicOrigFile)(struct FontconfigIFace *Self, FcAtomic * atomic);
	FcBool APICALL (*FcAtomicReplaceOrig)(struct FontconfigIFace *Self, FcAtomic * atomic);
	void APICALL (*FcAtomicDeleteNew)(struct FontconfigIFace *Self, FcAtomic * atomic);
	void APICALL (*FcAtomicUnlock)(struct FontconfigIFace *Self, FcAtomic * atomic);
	void APICALL (*FcAtomicDestroy)(struct FontconfigIFace *Self, FcAtomic * atomic);
	FcPattern * APICALL (*FcFontSetMatch)(struct FontconfigIFace *Self, FcConfig * config, FcFontSet * *sets, int nsets, FcPattern * p, FcResult * result);
	FcPattern * APICALL (*FcFontMatch)(struct FontconfigIFace *Self, FcConfig * config, FcPattern * p, FcResult * result);
	FcPattern * APICALL (*FcFontRenderPrepare)(struct FontconfigIFace *Self, FcConfig * config, FcPattern * pat, FcPattern * font);
	FcFontSet * APICALL (*FcFontSetSort)(struct FontconfigIFace *Self, FcConfig * config, FcFontSet * *sets, int nsets, FcPattern * p, FcBool trim, FcCharSet * *csp, FcResult * result);
	FcFontSet * APICALL (*FcFontSort)(struct FontconfigIFace *Self, FcConfig * config, FcPattern * p, FcBool trim, FcCharSet * *csp, FcResult * result);
	void APICALL (*FcFontSetSortDestroy)(struct FontconfigIFace *Self, FcFontSet * fs);
	FcMatrix * APICALL (*FcMatrixCopy)(struct FontconfigIFace *Self, const FcMatrix * mat);
	FcBool APICALL (*FcMatrixEqual)(struct FontconfigIFace *Self, const FcMatrix * mat1, const FcMatrix * mat2);
	void APICALL (*FcMatrixMultiply)(struct FontconfigIFace *Self, FcMatrix * result, const FcMatrix * a, const FcMatrix * b);
	void APICALL (*FcMatrixRotate)(struct FontconfigIFace *Self, FcMatrix * m, double c, double s);
	void APICALL (*FcMatrixScale)(struct FontconfigIFace *Self, FcMatrix * m, double sx, double sy);
	void APICALL (*FcMatrixShear)(struct FontconfigIFace *Self, FcMatrix * m, double sh, double sv);
	FcBool APICALL (*FcNameRegisterObjectTypes)(struct FontconfigIFace *Self, const FcObjectType * types, int ntype);
	FcBool APICALL (*FcNameUnregisterObjectTypes)(struct FontconfigIFace *Self, const FcObjectType * types, int ntype);
	const FcObjectType * APICALL (*FcNameGetObjectType)(struct FontconfigIFace *Self, const char * object);
	FcBool APICALL (*FcNameRegisterConstants)(struct FontconfigIFace *Self, const FcConstant * consts, int nconsts);
	FcBool APICALL (*FcNameUnregisterConstants)(struct FontconfigIFace *Self, const FcConstant * consts, int nconsts);
	const FcConstant * APICALL (*FcNameGetConstant)(struct FontconfigIFace *Self, const FcChar8 * string);
	const FcConstant * APICALL (*FcNameGetConstantFor)(struct FontconfigIFace *Self, const FcChar8 * string, const char * object);
	FcBool APICALL (*FcNameConstant)(struct FontconfigIFace *Self, const FcChar8 * string, int * result);
	FcPattern * APICALL (*FcNameParse)(struct FontconfigIFace *Self, const FcChar8 * name);
	FcChar8 * APICALL (*FcNameUnparse)(struct FontconfigIFace *Self, FcPattern * pat);
	FcPattern * APICALL (*FcPatternCreate)(struct FontconfigIFace *Self);
	FcPattern * APICALL (*FcPatternDuplicate)(struct FontconfigIFace *Self, const FcPattern * p);
	void APICALL (*FcPatternReference)(struct FontconfigIFace *Self, FcPattern * p);
	FcPattern * APICALL (*FcPatternFilter)(struct FontconfigIFace *Self, FcPattern * p, const FcObjectSet * os);
	void APICALL (*FcValueDestroy)(struct FontconfigIFace *Self, FcValue v);
	FcBool APICALL (*FcValueEqual)(struct FontconfigIFace *Self, FcValue va, FcValue vb);
	FcValue APICALL (*FcValueSave)(struct FontconfigIFace *Self, FcValue v);
	void APICALL (*FcPatternDestroy)(struct FontconfigIFace *Self, FcPattern * p);
	FcBool APICALL (*FcPatternEqual)(struct FontconfigIFace *Self, const FcPattern * pa, const FcPattern * pb);
	FcBool APICALL (*FcPatternEqualSubset)(struct FontconfigIFace *Self, const FcPattern * pa, const FcPattern * pb, const FcObjectSet * os);
	FcChar32 APICALL (*FcPatternHash)(struct FontconfigIFace *Self, const FcPattern * p);
	FcBool APICALL (*FcPatternAdd)(struct FontconfigIFace *Self, FcPattern * p, const char * object, FcValue value, FcBool append);
	FcBool APICALL (*FcPatternAddWeak)(struct FontconfigIFace *Self, FcPattern * p, const char * object, FcValue value, FcBool append);
	FcResult APICALL (*FcPatternGet)(struct FontconfigIFace *Self, const FcPattern * p, const char * object, int id, FcValue * v);
	FcResult APICALL (*FcPatternGetWithBinding)(struct FontconfigIFace *Self, const FcPattern * p, const char * object, int id, FcValue * v, FcValueBinding * b);
	FcBool APICALL (*FcPatternDel)(struct FontconfigIFace *Self, FcPattern * p, const char * object);
	FcBool APICALL (*FcPatternRemove)(struct FontconfigIFace *Self, FcPattern * p, const char * object, int id);
	FcBool APICALL (*FcPatternAddInteger)(struct FontconfigIFace *Self, FcPattern * p, const char * object, int i);
	FcBool APICALL (*FcPatternAddDouble)(struct FontconfigIFace *Self, FcPattern * p, const char * object, double d);
	FcBool APICALL (*FcPatternAddString)(struct FontconfigIFace *Self, FcPattern * p, const char * object, const FcChar8 * s);
	FcBool APICALL (*FcPatternAddMatrix)(struct FontconfigIFace *Self, FcPattern * p, const char * object, const FcMatrix * s);
	FcBool APICALL (*FcPatternAddCharSet)(struct FontconfigIFace *Self, FcPattern * p, const char * object, const FcCharSet * c);
	FcBool APICALL (*FcPatternAddBool)(struct FontconfigIFace *Self, FcPattern * p, const char * object, FcBool b);
	FcBool APICALL (*FcPatternAddLangSet)(struct FontconfigIFace *Self, FcPattern * p, const char * object, const FcLangSet * ls);
	FcBool APICALL (*FcPatternAddRange)(struct FontconfigIFace *Self, FcPattern * p, const char * object, const FcRange * r);
	FcResult APICALL (*FcPatternGetInteger)(struct FontconfigIFace *Self, const FcPattern * p, const char * object, int n, int * i);
	FcResult APICALL (*FcPatternGetDouble)(struct FontconfigIFace *Self, const FcPattern * p, const char * object, int n, double * d);
	FcResult APICALL (*FcPatternGetString)(struct FontconfigIFace *Self, const FcPattern * p, const char * object, int n, FcChar8 ** s);
	FcResult APICALL (*FcPatternGetMatrix)(struct FontconfigIFace *Self, const FcPattern * p, const char * object, int n, FcMatrix * *s);
	FcResult APICALL (*FcPatternGetCharSet)(struct FontconfigIFace *Self, const FcPattern * p, const char * object, int n, FcCharSet * *c);
	FcResult APICALL (*FcPatternGetBool)(struct FontconfigIFace *Self, const FcPattern * p, const char * object, int n, FcBool * b);
	FcResult APICALL (*FcPatternGetLangSet)(struct FontconfigIFace *Self, const FcPattern * p, const char * object, int n, FcLangSet * *ls);
	FcResult APICALL (*FcPatternGetRange)(struct FontconfigIFace *Self, const FcPattern * p, const char * object, int id, FcRange * *r);
	FcPattern * APICALL (*FcPatternVaBuild)(struct FontconfigIFace *Self, FcPattern * p, va_list va);
	FcPattern * APICALL (*FcPatternBuild)(struct FontconfigIFace *Self, FcPattern * p, ...);
	FcChar8 * APICALL (*FcPatternFormat)(struct FontconfigIFace *Self, FcPattern * pat, const FcChar8 * format);
	FcRange * APICALL (*FcRangeCreateDouble)(struct FontconfigIFace *Self, double begin, double end);
	FcRange * APICALL (*FcRangeCreateInteger)(struct FontconfigIFace *Self, FcChar32 begin, FcChar32 end);
	void APICALL (*FcRangeDestroy)(struct FontconfigIFace *Self, FcRange * range);
	FcRange * APICALL (*FcRangeCopy)(struct FontconfigIFace *Self, const FcRange * r);
	FcBool APICALL (*FcRangeGetDouble)(struct FontconfigIFace *Self, const FcRange * range, double * begin, double * end);
	void APICALL (*FcPatternIterStart)(struct FontconfigIFace *Self, const FcPattern * pat, FcPatternIter * iter);
	FcBool APICALL (*FcPatternIterNext)(struct FontconfigIFace *Self, const FcPattern * pat, FcPatternIter * iter);
	FcBool APICALL (*FcPatternIterEqual)(struct FontconfigIFace *Self, const FcPattern * p1, FcPatternIter * i1, const FcPattern * p2, FcPatternIter * i2);
	FcBool APICALL (*FcPatternFindIter)(struct FontconfigIFace *Self, const FcPattern * pat, FcPatternIter * iter, const char * object);
	FcBool APICALL (*FcPatternIterIsValid)(struct FontconfigIFace *Self, const FcPattern * pat, FcPatternIter * iter);
	const char * APICALL (*FcPatternIterGetObject)(struct FontconfigIFace *Self, const FcPattern * pat, FcPatternIter * iter);
	int APICALL (*FcPatternIterValueCount)(struct FontconfigIFace *Self, const FcPattern * pat, FcPatternIter * iter);
	FcResult APICALL (*FcPatternIterGetValue)(struct FontconfigIFace *Self, const FcPattern * pat, FcPatternIter * iter, int id, FcValue * v, FcValueBinding * b);
	int APICALL (*FcWeightFromOpenType)(struct FontconfigIFace *Self, int ot_weight);
	double APICALL (*FcWeightFromOpenTypeDouble)(struct FontconfigIFace *Self, double ot_weight);
	int APICALL (*FcWeightToOpenType)(struct FontconfigIFace *Self, int fc_weight);
	double APICALL (*FcWeightToOpenTypeDouble)(struct FontconfigIFace *Self, double fc_weight);
	FcChar8 * APICALL (*FcStrCopy)(struct FontconfigIFace *Self, const FcChar8 * s);
	FcChar8 * APICALL (*FcStrCopyFilename)(struct FontconfigIFace *Self, const FcChar8 * s);
	FcChar8 * APICALL (*FcStrPlus)(struct FontconfigIFace *Self, const FcChar8 * s1, const FcChar8 * s2);
	void APICALL (*FcStrFree)(struct FontconfigIFace *Self, FcChar8 * s);
	FcChar8 * APICALL (*FcStrDowncase)(struct FontconfigIFace *Self, const FcChar8 * s);
	int APICALL (*FcStrCmpIgnoreCase)(struct FontconfigIFace *Self, const FcChar8 * s1, const FcChar8 * s2);
	int APICALL (*FcStrCmp)(struct FontconfigIFace *Self, const FcChar8 * s1, const FcChar8 * s2);
	const FcChar8 * APICALL (*FcStrStrIgnoreCase)(struct FontconfigIFace *Self, const FcChar8 * s1, const FcChar8 * s2);
	const FcChar8 * APICALL (*FcStrStr)(struct FontconfigIFace *Self, const FcChar8 * s1, const FcChar8 * s2);
	int APICALL (*FcUtf8ToUcs4)(struct FontconfigIFace *Self, const FcChar8 * src_orig, FcChar32 * dst, int len);
	FcBool APICALL (*FcUtf8Len)(struct FontconfigIFace *Self, const FcChar8 * string, int len, int * nchar, int * wchar);
	int APICALL (*FcUcs4ToUtf8)(struct FontconfigIFace *Self, FcChar32 ucs4, FcChar8 dest[FC_UTF8_MAX_LEN]);
	int APICALL (*FcUtf16ToUcs4)(struct FontconfigIFace *Self, const FcChar8 * src_orig, FcEndian endian, FcChar32 * dst, int len);
	FcBool APICALL (*FcUtf16Len)(struct FontconfigIFace *Self, const FcChar8 * string, FcEndian endian, int len, int * nchar, int * wchar);
	FcChar8 * APICALL (*FcStrBuildFilename)(struct FontconfigIFace *Self, const FcChar8 * path, ... );
	FcChar8 * APICALL (*FcStrDirname)(struct FontconfigIFace *Self, const FcChar8 * file);
	FcChar8 * APICALL (*FcStrBasename)(struct FontconfigIFace *Self, const FcChar8 * file);
	FcStrSet * APICALL (*FcStrSetCreate)(struct FontconfigIFace *Self);
	FcBool APICALL (*FcStrSetMember)(struct FontconfigIFace *Self, FcStrSet * set, const FcChar8 * s);
	FcBool APICALL (*FcStrSetEqual)(struct FontconfigIFace *Self, FcStrSet * sa, FcStrSet * sb);
	FcBool APICALL (*FcStrSetAdd)(struct FontconfigIFace *Self, FcStrSet * set, const FcChar8 * s);
	FcBool APICALL (*FcStrSetAddFilename)(struct FontconfigIFace *Self, FcStrSet * set, const FcChar8 * s);
	FcBool APICALL (*FcStrSetDel)(struct FontconfigIFace *Self, FcStrSet * set, const FcChar8 * s);
	void APICALL (*FcStrSetDestroy)(struct FontconfigIFace *Self, FcStrSet * set);
	FcStrList * APICALL (*FcStrListCreate)(struct FontconfigIFace *Self, FcStrSet * set);
	void APICALL (*FcStrListFirst)(struct FontconfigIFace *Self, FcStrList * list);
	FcChar8 * APICALL (*FcStrListNext)(struct FontconfigIFace *Self, FcStrList * list);
	void APICALL (*FcStrListDone)(struct FontconfigIFace *Self, FcStrList * list);
	FcBool APICALL (*FcConfigParseAndLoad)(struct FontconfigIFace *Self, FcConfig * config, const FcChar8 * file, FcBool complain);
	FcBool APICALL (*FcConfigParseAndLoadFromMemory)(struct FontconfigIFace *Self, FcConfig * config, const FcChar8 * buffer, FcBool complain);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* FONTCONFIG_INTERFACE_DEF_H */
